# Generated by Django 2.2.6 on 2020-06-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cert_type', models.CharField(choices=[('COAL', 'Coal Sampling and Analysis Certificate'), ('DGA', 'DGA Test Certificate')], default='COAL', max_length=4)),
                ('upload', models.FileField(upload_to='uploads\\')),
            ],
        ),
    ]
