# Generated by Django 3.0.7 on 2020-07-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cert_type', models.CharField(choices=[('COAL', 'Coal Sampling and Analysis Certificate'), ('DGA', 'DGA Test Certificate')], default='COAL', max_length=4)),
                ('upload', models.FileField(upload_to='uploads\\')),
                ('extraction_status', models.CharField(choices=[('E', 'Extracted'), ('Q', 'Queued'), ('NE', 'Not Extracted'), ('X', 'Extraction Failed')], default='NE', max_length=2)),
                ('tag_configuration_id', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='CoalParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
                ('parameters', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CoalParametersDividers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dividers', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CoalParametersSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedDataCSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cert_type', models.CharField(choices=[('COAL', 'Coal Sampling and Analysis Certificate'), ('DGA', 'DGA Test Certificate')], default='COAL', max_length=4)),
                ('filepath', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TagConfigurationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('transformation', models.CharField(max_length=9999)),
                ('reference', models.FileField(blank=True, upload_to='configurations\\')),
            ],
        ),
        migrations.CreateModel(
            name='UserActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('activity', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('P', 'In Progress'), ('C', 'Completed'), ('X', 'Failed')], default='P', max_length=4)),
            ],
        ),
    ]
