# Generated by Django 2.2.6 on 2020-06-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_coalparameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoalParametersDividers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dividers', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CoalParametersSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections', models.CharField(max_length=100)),
            ],
        ),
    ]
