# Generated by Django 2.2.6 on 2020-06-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_coalparametersdividers_coalparameterssection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedDataCSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cert_type', models.CharField(choices=[('COAL', 'Coal Sampling and Analysis Certificate'), ('DGA', 'DGA Test Certificate')], default='COAL', max_length=4)),
                ('filepath', models.CharField(max_length=100)),
            ],
        ),
    ]
