# Generated by Django 3.0.7 on 2020-06-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_extracteddatacsv'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='extraction_status',
            field=models.CharField(choices=[('E', 'Extracted'), ('Q', 'Queued'), ('NE', 'Not Extracted')], default='NE', max_length=2),
        ),
    ]
