# Generated by Django 3.0.7 on 2020-06-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_certificate_extraction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='extraction_status',
            field=models.CharField(choices=[('E', 'Extracted'), ('Q', 'Queued'), ('NE', 'Not Extracted'), ('X', 'Extraction Failed')], default='NE', max_length=2),
        ),
    ]
