# Generated by Django 3.0.7 on 2020-07-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200621_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('activity', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('P', 'In Progress'), ('C', 'Completed'), ('X', 'Failed')], default='P', max_length=4)),
            ],
        ),
    ]
