# Generated by Django 3.0.7 on 2020-07-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_useractivities'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagConfigurationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('conf_type', models.CharField(choices=[('SB', 'String Builder'), ('TL', 'Table Lookup')], default='TL', max_length=4)),
                ('transformers', models.CharField(max_length=100)),
                ('reference', models.FileField(upload_to='configurations\\')),
            ],
        ),
    ]
