# Generated by Django 3.0.7 on 2020-07-11 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_certificate_tag_configuration_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagconfigurationtemplate',
            name='conf_type',
        ),
    ]
