# Generated by Django 3.0.7 on 2020-07-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_tagconfigurationtemplate_conf_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagconfigurationtemplate',
            name='transformers',
            field=models.CharField(max_length=9999),
        ),
    ]
