# Generated by Django 3.0.7 on 2020-07-11 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200711_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagconfigurationtemplate',
            old_name='transformers',
            new_name='transformation',
        ),
    ]
