# Generated by Django 3.0.7 on 2020-07-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200712_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagconfigurationtemplate',
            name='reference',
            field=models.FileField(blank=True, upload_to='configurations\\'),
        ),
    ]
